name: PHP

on: ["push", "pull_request"]

jobs:
  build_and_test:
    name: Build and test paranoid with ${{ matrix.php-version }}
    strategy:
      matrix:
        php-version: ["7.4"]

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: PHP version
        run: |
          php --version

      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install node packages
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - run: yarn --ignore-scripts
        shell: bash

      - name: Create local node, deploy and test
        run: |
          yarn hardhat node --config hardhat.config.ts &
          sleep 10 
          yarn hardhat ignition deploy ./ignition/modules/TSX.ts --network localhost 
          yarn hardhat ignition deploy ./ignition/modules/TSX2.ts --network localhost
          vendor/bin/phpunit --coverage-clover=coverage.xml
          npx kill-port 8545

      - name: Create local node, deploy and test on the pre-EIP1559 (Berlin hardfork)
        run: |
          yarn hardhat node --config hardhat-berlin.config.ts &
          sleep 10 
          yarn hardhat ignition deploy ./ignition/modules/TSX.ts --network localhost 
          yarn hardhat ignition deploy ./ignition/modules/TSX2.ts --network localhost
          vendor/bin/phpunit --coverage-clover=coverage.xml

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
